vm:
  box: bento/ubuntu-16.04
  hostname: fighter
  network:
    private_network:
      ip: 192.168.33.101
chef_solo:
  cookbooks:
    apt:
      version: ~> 6.1.4
      includes:
        - apt::default
    timezone_iii:
      version: ~> 1.1.6
      includes:
        - timezone_iii::default
      attributes:
        timezone: UTC
